/**
 * Pipeline-specific configurations for header mapping
 * Defines field mappings for Pipeline 02 and Pipeline 04
 */

import type { HeaderMappingConfig } from './header-mapping.js';

/**
 * Pipeline 02 - Desvio de Carregamento
 * Fields: data_ref, turno, equipamento, curral_codigo, dieta_nome, kg_planejado, kg_real, desvio_kg, desvio_pct
 */
export const pipeline02Config: HeaderMappingConfig = {
  caseSensitive: false,
  strict: false,
  removePrefix: '',
  removeSuffix: '',
  fields: {
    data_ref: {
      canonical: 'data_ref',
      required: true,
      type: 'date',
      aliases: [
        'data',
        'date',
        'data_referencia',
        'data_ref',
        'dt_ref',
        'dt_referencia',
        'fecha',
        'datum',
      ],
    },
    turno: {
      canonical: 'turno',
      required: false,
      type: 'string',
      aliases: [
        'turno',
        'shift',
        'periodo',
        'horario',
        'shift_period',
        'work_shift',
      ],
    },
    equipamento: {
      canonical: 'equipamento',
      required: true,
      type: 'string',
      aliases: [
        'equipamento',
        'equipment',
        'maquina',
        'machine',
        'vagao',
        'wagon',
        'bahman',
        'siloking',
        'equip',
        'eq',
      ],
    },
    curral_codigo: {
      canonical: 'curral_codigo',
      required: true,
      type: 'string',
      aliases: [
        'curral',
        'curral_codigo',
        'curral_cod',
        'pen',
        'pen_code',
        'paddock',
        'lot',
        'corral',
        'codigo_curral',
        'cod_curral',
      ],
    },
    dieta_nome: {
      canonical: 'dieta_nome',
      required: false,
      type: 'string',
      aliases: [
        'dieta',
        'dieta_nome',
        'diet',
        'diet_name',
        'ration',
        'feed',
        'formula',
        'recipe',
        'nome_dieta',
      ],
    },
    kg_planejado: {
      canonical: 'kg_planejado',
      required: true,
      type: 'number',
      aliases: [
        'kg_planejado',
        'planejado',
        'planned',
        'planned_kg',
        'target',
        'target_kg',
        'objetivo',
        'meta',
        'previsto',
        'programado',
      ],
    },
    kg_real: {
      canonical: 'kg_real',
      required: true,
      type: 'number',
      aliases: [
        'kg_real',
        'real',
        'actual',
        'actual_kg',
        'delivered',
        'delivered_kg',
        'realizado',
        'entregue',
        'efetivo',
      ],
    },
    desvio_kg: {
      canonical: 'desvio_kg',
      required: false,
      type: 'number',
      aliases: [
        'desvio',
        'desvio_kg',
        'deviation',
        'deviation_kg',
        'variance',
        'variance_kg',
        'diferenca',
        'diff',
        'delta',
      ],
    },
    desvio_pct: {
      canonical: 'desvio_pct',
      required: false,
      type: 'number',
      aliases: [
        'desvio_pct',
        'desvio_percent',
        'desvio_%',
        'deviation_pct',
        'deviation_%',
        'variance_pct',
        'percent_deviation',
        'porcentagem',
        '%_desvio',
      ],
    },
  },
};

/**
 * Pipeline 04 - Trato por Curral
 * Fields: data_ref, hora_trato, curral_codigo, trateiro, dieta_nome, quantidade_kg, observacoes
 */
export const pipeline04Config: HeaderMappingConfig = {
  caseSensitive: false,
  strict: false,
  removePrefix: '',
  removeSuffix: '',
  fields: {
    data_ref: {
      canonical: 'data_ref',
      required: true,
      type: 'date',
      aliases: [
        'data',
        'date',
        'data_referencia',
        'data_ref',
        'dt_ref',
        'dt_referencia',
        'fecha',
        'datum',
      ],
    },
    hora_trato: {
      canonical: 'hora_trato',
      required: false,
      type: 'string',
      aliases: [
        'hora',
        'time',
        'hora_trato',
        'feeding_time',
        'horario',
        'h_trato',
        'trato_hora',
        'feeding_hour',
      ],
    },
    curral_codigo: {
      canonical: 'curral_codigo',
      required: true,
      type: 'string',
      aliases: [
        'curral',
        'curral_codigo',
        'curral_cod',
        'pen',
        'pen_code',
        'paddock',
        'lot',
        'corral',
        'codigo_curral',
        'cod_curral',
      ],
    },
    trateiro: {
      canonical: 'trateiro',
      required: false,
      type: 'string',
      aliases: [
        'trateiro',
        'feeder',
        'operator',
        'operador',
        'funcionario',
        'employee',
        'worker',
        'nome_trateiro',
        'tratador',
      ],
    },
    dieta_nome: {
      canonical: 'dieta_nome',
      required: false,
      type: 'string',
      aliases: [
        'dieta',
        'dieta_nome',
        'diet',
        'diet_name',
        'ration',
        'feed',
        'formula',
        'recipe',
        'nome_dieta',
      ],
    },
    quantidade_kg: {
      canonical: 'quantidade_kg',
      required: true,
      type: 'number',
      aliases: [
        'quantidade',
        'quantidade_kg',
        'kg',
        'amount',
        'amount_kg',
        'weight',
        'peso',
        'qtd',
        'qtde',
        'volume',
        'delivered',
      ],
    },
    observacoes: {
      canonical: 'observacoes',
      required: false,
      type: 'string',
      aliases: [
        'observacoes',
        'obs',
        'notes',
        'comments',
        'remarks',
        'comentarios',
        'notas',
        'observation',
        'memo',
        'description',
      ],
    },
  },
};